AppBundle\Entity\CoworkerHasTask:
    type: entity
    table: coworker_has_task
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        coworker:
            targetEntity: AppBundle\Entity\Coworker
            inversedBy: coworkerHasTasks
            joinColumn:
                name: coworker_id
                referencedColumnName: id
                onDelete: CASCADE
        task:
            targetEntity: AppBundle\Entity\Task
            inversedBy: coworkerHasTasks
            joinColumn:
                name: task_id
                referencedColumnName: id
                onDelete: CASCADE

    lifecycleCallbacks: {  }