AppBundle\Entity\EventType:
    type: entity

    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO

        fields:
            name:
                column: name
                type: string
                length: 100

        oneToMany:
            eventHasTypes:
                targetEntity: AppBundle\Entity\EventHasType
                mappedBy: eventType

    lifecycleCallbacks: {  }