AppBundle\Entity\Event:
    type: entity
    table: event
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO

    fields:
        date:
            column: date
            type: datetime
        timeStart:
            column: time_start
            type: datetime
        timeEnd:
            column: time_end
            nullable: true
            type: datetime
        employeeStartingTime:
            column: employee_starting_time
            nullable: true
            type: datetime
        guests:
            column: guests
            type: integer
        description:
            type: text
            nullable: true
            length: 65535

    oneToMany:
        schedules:
            targetEntity: AppBundle\Entity\Schedule
            mappedBy: event
        eventHasTypes:
            targetEntity: AppBundle\Entity\EventHasType
            mappedBy: event
    manyToOne:
        manager:
            targetEntity: AppBundle\Entity\User
            inversedBy: events
            joinColumn:
                name: manager_id
                referenceColumnName: id
                onDelete: SET NULL
    lifecycleCallbacks: {  }