AppBundle\Entity\Location:
    type: entity
    table: location
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO
    fields:
        location:
            column: location
            type: string
            length: 100

    oneToMany:
        scheduleHasLocations:
            targetEntity: AppBundle\Entity\ScheduleHasLocation
            mappedBy: location

    lifecycleCallbacks: {  }