AppBundle\Entity\Role:
    type: entity
    table: role
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            column: name
            type: string
            length: 100
        type:
            column: type
            type: integer


    oneToMany:
        userHasRoles:
            targetEntity: AppBundle\Entity\UserHasRole
            mappedBy: role

    lifecycleCallbacks: {  }