AppBundle\Entity\ScheduleHasLocation:
    type: entity
    table: schedule_has_location
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO

    manyToOne:
        schedule:
            targetEntity: AppBundle\Entity\Schedule
            inversedBy: scheduleHasLocations
            joinColumn:
                name: schedule_id
                referencedColumnName: id
                onDelete: CASCADE
        location:
            targetEntity: AppBundle\Entity\Location
            inversedBy: scheduleHasLocations
            joinColumn:
                name: location_id
                referencedColumnName: id
                onDelete: CASCADE

    lifecycleCallbacks: {  }