AppBundle\Entity\Task:
    type: entity
    table: task
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 45
        description:
            column: description
            type: text

    oneToMany:
        schedules:
            targetEntity: AppBundle\Entity\Schedule
            mappedBy: task
        coworkerHasTasks:
            targetEntity: AppBundle\Entity\CoworkerHasTask
            mappedBy: task

    lifecycleCallbacks: {  }