AppBundle\Entity\User:
    type: entity

    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO

        fields:
            firstName:
                column: first_name
                type: string
                length: 60
            lastName:
                column: last_name
                type: string
                length: 60
            email:
                column: email
                type: string
                unique: true
                length: 60
            password:
                column: password
                type: string
                nullable: true
                length: 255


        oneToMany:
            events:
                targetEntity: AppBundle\Entity\Event
                mappedBy: user
            userHasRoles:
                targetEntity: AppBundle\Entity\UserHasRole
                mappedBy: user

    lifecycleCallbacks: {  }