# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  # CONTROLLERS
  app.controller.base:
    class: AppBundle\Controller\BaseController
    arguments:
        - '@templating'
        - '@session'
        - '@router'
        - '@translator'
        - '@doctrine.orm.entity_manager'
        - '@request_stack'
        - '@form.factory'
        - '@service_container'
        - '@security.authentication_utils'
        - '@security.token_storage'
        - '@security.authorization_checker'

  app.controller.dashboard:
    class: AppBundle\Controller\DashboardController
    parent: app.controller.base

  app.controller.coworker:
      class: AppBundle\Controller\CoworkerController
      parent: app.controller.base

  app.controller.event:
      class: AppBundle\Controller\EventController
      parent: app.controller.base

  app.controller.schedule:
      class: AppBundle\Controller\ScheduleController
      parent: app.controller.base

  app.controller.settings:
      class: AppBundle\Controller\SettingsController
      parent: app.controller.base

  app.controller.security:
      class: AppBundle\Controller\SecurityController
      parent: app.controller.base

  app.controller.user:
      class: AppBundle\Controller\UserController
      parent: app.controller.base

  app.controller.task:
      class: AppBundle\Controller\TaskController
      parent: app.controller.base

  app.controller.location:
      class: AppBundle\Controller\LocationController
      parent: app.controller.base

  # FORM
  app.form.error.form_error:
      class: AppBundle\Form\Error\FormError
      arguments:
          - '@translator'

  app.form.type.user:
      class: AppBundle\Form\UserType
      arguments:
          - '@translator'
      tags:
          - { name: form.type }

  app.form.type.task:
      class: AppBundle\Form\TaskType
      arguments:
          - '@translator'
      tags:
          - { name: form.type }

  app.form.type.location:
      class: AppBundle\Form\LocationType
      arguments:
          - '@translator'
      tags:
          - { name: form.type }